import os

#os.system("pwd")
#os.system("apt install")
print("подготовка доп. программ...")
os.system("sudo apt update && apt upgrade")
os.system("sudo apt install python2 && apt install python3 && apt install git && apt install wget && apt-get install python3-pip && apt install adb && apt install python && apt install dnsutils && apt install curl && apt install Perl")
os.system("apt update && apt upgrade")
os.system(" apt install python2 && apt install python3 && apt install git && apt install wget && apt-get install python3-pip && apt install adb && apt install python && apt install dnsutils && apt install curl && apt install Perl")
os.system("clear")
print("--------------доступна установка 15 программ----------------")
def install():
	print("1-rat android")
	print("2-weeman")
	print("3-expcamera")
	print("4-phonesploit")
	print("5-ipdrone")
	print("6-lite-ddos")
	print("7-giper ddos")
	print("8-nmap")
	print("9-hydra")
	print("10-sql map")
	print("11-wireshark")
	print("12-social-tool-keet")
	print("13-nikto")
	print("14-tool-kit")
	print("0-выйти")
	pro = int(input("введите номер программы"))
	if(pro == 0):
		os.system("^C")
	if(pro == 8):
		print("installing...")
		os.system("apt install curl")
		os.system("apt install Nmap")
		os.system("sudo apt install curl")
		os.system("sudo apt install Nmap")
		install()
	if(pro == 1):
		print("installing...")
		os.system("git clone https://github.com/PyRAT-svg/msfgaf")
		os.system("cd msfgaf")
		os.system("python2 install.py")
		
		install()
	if(pro == 2):
		print("installing...")
		os.system("git clone https://github.com/evait-security/weeman")
		os.system("cd weeman")
		os.system("ls")
		os.system("python2 weeman.py")
	if(pro == 3):
		print("installing...")
		os.system("git clone https://github.com/vanpersiexp/expcamera")
		os.system("cd expcamera")
		os.system("pip3 install -r related.txt")
 #	os.system("")
		install()
	if (pro == 4):
		print("installing...")
		os.system("git clone https://github.com/aerosol-can/PhoneSploit")
		os.system("cd PhoneSploit")
		os.system("pip3 install colorama")
		os.system("python3 phonesploit.pyz")
		
		install()
	if (pro == 5):
		print("installing...")
		os.system("git clone https://github.com/noob-hackers/ipdrone")
		os.system("cd ipdrone")
		os.system("python ipdrone.py ")
		install()
	if (pro == 6):
		print("installing...")
		os.system("git clone https://github.com/gkbrk/slowloris")
		os.system("cd slowloris")
		os.system("python3 slowloris.py")
		install()
	if (pro == 7):
		print("installing...")
		os.system("git clone https://github.com/CruzTed/Hammer")
		os.system("cd Hammer")
		os.system("python3 hammer.py")
		install()
	if (pro == 9):
		print("installing...")
		os.system("sudo apt install hydra")
		os.system("apt install hydra")
		install()
	if (pro == 10):
		print("installing...")
		os.system("git clone https://github.com/sqlmapproject/sqlmap")
		os.system("cd sqlmap")
		os.system("chmod +x sqlmap.py")
		os.system("python2 sqlmap.py")
		install()
	if (pro == 11):
		print("installing...")
		os.system("apt install xterm && apt install tigervnc && apt install tigervnc-viever && apt install x11-repo && apt install Wireshark-gtk")
		os.system("sudo apt install xterm && apt install tigervnc && apt install tigervnc-viever && apt install x11-repo && apt install Wireshark-gtk ")
		install()
	if (pro == 12):
		print("installing...")
		os.system("curl -LO https://raw.githubusercontent.com/Hax4us/setoolkit/master/setoolkit.sh")
		os.system("sh setoolkit.sh")
		os.system("./setup.py install ")
		os.system("./setoolkit")
		install()
	if (pro == 13):
		print("installing...")
		os.system("git clone https://github.com/sullo/nikto")
		os.system("cd nikto/program")
		install()
	if (pro == 14):
		print("installing...")
		os.system("git clone https://github.com/Manisso/fsociety")
		os.system("cd fsociety")
		os.system("chmod +x install.sh")
		os.system("./install.sh")
		install()
#	if (pro == 15):
	#	print("installing...")
	#	os.system("")
#		install()
install()